name: Pull Request Example
'on':
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run linting
        run: yarn lint
      - name: Build project
        run: yarn build
      - name: Run tests
        run: yarn test
